### ISSUE TITLE
Improve Docs

### ISSUE THREAD

**Issue by johnwbaxter** [ryssbowh/craft-triggers#1]
Can you give the docs a bit of work around actions specifically please?

It's not clear if the user needs to create their own custom module to do be able to add an action for your plugin or use the existing modules folder or what.

Your action sample code is a bit light on detail too for people not expert in creating Craft modules etc. A *complete* example of an action would really help a lot of people use your plugin.

I certainly know devs that would like to use this but wouldn't get enough from your docs on actions to be able to get going.

Thanks!

**Comment by ryssbowh** [comment]
Hi,

I can't really give a complete example as it depends on your application, if you prefer to define modules or plugins or if you define new triggers/conditions/actions on a Craft plugin that you intend to register on the store.

I've added an example for a local plugin within a `plugins` folder as described by the [Craft docs](https://craftcms.com/docs/3.x/extend/plugin-guide.html) in the [examples folder](https://github.com/ryssbowh/craft-triggers/tree/master/examples)

**Comment by johnwbaxter** [comment]
That is absolutely perfect, that's exactly what was missing! Thank you :)
