### ISSUE TITLE
Error on When entry is saved 

### ISSUE THREAD

**Issue by bjerenec** [ryssbowh/craft-triggers#10]
**Describe the bug**
After updating Craft v4 to Craft v5 and triggers 3.0.0 I cannot open saved trigger with type "When entry is saved".
I get this error: Getting unknown property: craft\web\Application::sections.

It seems that craft has deprecated `Sections` service, error is triggered by:
`return \Craft::$app->sections->getSectionByUid($section)->name;`

It looks like Craft v5 added/merged these methods to the `Entries` service:
https://docs.craftcms.com/api/v5/craft-services-entries.html#example-14

Creating new trigger of the same type also fails.

**To Reproduce**
1. Upgrade from craft v4 to v5 and to Trigger 3.0.0.
2. Open existing trigger of type "When entry is saved"

or

1. Create new Trigger
2. Select type "When entry is saved"

**Versions: **
 - PHP: 8.3.3
 - Triggers: 3.0.0
 - Craft CMS: 5.4.9

**Comment by ryssbowh** [comment]
Thanks for reporting, this has been fixed in 3.0.1
