### ISSUE TITLE
examples dont work

### ISSUE THREAD

**Issue by gixxy22** [ryssbowh/craft-triggers#2]
trying to use the examples, but they dont appear to work, composer complaining about cant find the base path.

seems to be a file case mismatch somewhere.

```
In Installer.php line 130:
                                                                         
  Couldn't install plugins/my-plugin: Unable to determine the base path  
                                                                         
```

**Comment by gixxy22** [comment]
Plugin.php needs renaming to MyPlugin.php, and there is a missing semicolon on line 38 of MyCondition.php.

I get this is just an example and would be renamed anyway but might be helpful to others.

**Comment by ryssbowh** [comment]
Thanks for reporting I've amended the examples
