### ISSUE TITLE
The Is New conditional is passing true even when the Entry is not new.

### ISSUE THREAD

**Issue by a-am** [ryssbowh/craft-triggers#3]
I have a Trigger setup using On Entry Save, one of the conditions is **Is New**, however no matter how many times I save the Entry it triggers the Action. 

**To Reproduce**
1. Create Trigger for **On Entry Save**.
2. Add condition **Is New** with **Is New** toggled on in the condition settings.
3. Add condition **Section** with specific section you will create an entry.
4. Create any action for testing purposes.
5. Create Entry in the Section, Save the Entry then resave the Entry again and the Action will be trigger every time you save.

**Versions: **
 - PHP: 8.0
 - Triggers: 2.0.3
 - Craft CMS: 4.0.3

**Comment by ryssbowh** [comment]
Most likely what is triggered is the revision or the draft, I rechecked it just now and it works as expected. Revisions and drafts are regular entries in Craft so you'd need to add conditions "is not a draft" and "is not a revision"

**Comment by a-am** [comment]
I have tried your suggestion, **Is new**, **Is not a draft** & **Is not a revision**, on initial save of an Entry and the Action doesn't get triggered. Is that the case for you?

**Comment by ryssbowh** [comment]
Apologies, there was a problem with this is new indeed. I fixed this in 2.0.5
