### ISSUE TITLE
Error on delete entry.

### ISSUE THREAD

**Issue by gixxy22** [ryssbowh/craft-triggers#4]
**Describe the bug**
Error when using on delete trigger:

Ryssbowh\CraftTriggers\models\triggers\EntryDeleted::Ryssbowh\CraftTriggers\models\triggers\{closure}(): Argument #1 ($e) must be of type craft\events\ModelEvent, yii\base\Event given

**To Reproduce**
1. create trigger with TYPE: When an entry is deleted.
2.  add a condition of a particular section.
3. delete an entry within that section.

**Versions: **
 - PHP: 8.0.19
 - Triggers: 1.0.7
 - Craft CMS: Craft Pro 3.7.44

**Comment by ryssbowh** [comment]
Thanks for reporting, fixed in 1.0.8
