### ISSUE TITLE
Category

### ISSUE THREAD

**Issue by wmdhosting** [ryssbowh/craft-triggers#5]
**feature request for a new trigger**
Is there a way to send mail when entry is published in **Section**  that contain specific **category**

**Comment by ryssbowh** [comment]
I don't understand, you mean have a condition to check if a field is present in a section's layout ?

**Comment by wmdhosting** [comment]
example..   entry published in **News** section triger action only if that Entry is related to specific category..

**Comment by ryssbowh** [comment]
This is out for Craft 3.x, in the 1.1.0 version. And in Craft 4 in the 2.1.0 version

**Comment by wmdhosting** [comment]
OK thx.. great :)

Just question..   in Action..  i have only Log a mesage.. 

Dont have action **send email**. as on image in docs..

**Comment by ryssbowh** [comment]
That action is defined by another plugin : https://github.com/ryssbowh/craft-emails
This plugin doesn't come with actions, as it's specific to your needs, have a look in the documentation to create your own plugin
