### ISSUE TITLE
Triggers triggering Twice for "When an entry is saved" condition

### ISSUE THREAD

**Issue by rspilhaus** [ryssbowh/craft-triggers#6]
Triggers seem to fire twice on the "when an entry is saved" condition. 

**Versions: **
 - PHP: 8.0.8
 - Craft CMS: 4.2.3

**Comment by ryssbowh** [comment]
They would be if you don't filter out the drafts and revisions : https://github.com/ryssbowh/craft-triggers/issues/3#issuecomment-1138170381

**Comment by rspilhaus** [comment]
Ah perfect. Thank you!
