### ISSUE TITLE
Selecting recipients by Twig

### ISSUE THREAD

**Issue by mprofitlich** [ryssbowh/craft-triggers#7]
**Is your feature request for a new trigger or a new condition.**
Request for a new **action**.

Use case: Depending on selections made in a frontend form, data saved to an entry should be mailed to different recipients. The recipients are also saved in the entry. 

Currently only fixed addresses, users and Mailchimp are possible recipients. 

Would it be possible to add a Twig textarea in the actions so that recipients could be taken from the database?

**Comment by ryssbowh** [comment]
Hi,
I think this is a question about the emails plugin, same than https://github.com/ryssbowh/craft-emails/issues/6 ?

I replied there

**Comment by mprofitlich** [comment]
It is. Thank you!
