### ISSUE TITLE
Error on Install after Update

### ISSUE THREAD

**Issue by beckbailey** [ryssbowh/craft-triggers#8]
**Describe the bug**
I tried to update Triggers and Emails through the Craft Admin interface and received an internal server error. I removed the plugins via the cli and tried to install via plugin store and received the error attached.

This was also my issue with Emails https://github.com/ryssbowh/craft-emails/issues/5. Not sure if they are somehow related. 

**To Reproduce**
1.  See above.
2. 
3.

**Versions: **
 - PHP: 7.4.29
 - Triggers: latest
 - Craft CMS: 3.7.57
 - MySQL: 5.7.22

[error.txt](https://github.com/ryssbowh/craft-triggers/files/9824278/error.txt)

**Comment by ryssbowh** [comment]
Thanks for reporting, this is fixed in 1.1.3
